name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      only_affected:
        description: "Run only affected packages"
        default: 'true'
        required: false
        type: boolean


env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: npx nx-cloud start-ci-run
      - if: ${{ !github.event.inputs.only_affected || github.event.inputs.only_affected == 'true' }}
        run: npx nx affected --target=test --parallel
      - if: ${{ github.event.inputs.only_affected == 'false' }}
        run: npx nx run-many --target=test --all --parallel
      - run: npx nx-cloud stop-all-agents
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: npx nx-cloud start-ci-run
      - if: ${{ github.event.inputs.only_affected == 'true' }}
        run: npx nx affected --target=test --parallel
      - if: ${{ github.event.inputs.only_affected == 'false' }}
        run: npx nx run-many --target=test --all --parallel
      - run: npx nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Nx Agent
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent